// This file was generated by the Gtk# code generator.
// Any changes made will be lost if regenerated.

#include <gtk/gtk.h>

void gtksharp_cellrenderer_override_get_request_mode (GtkCellRendererClass *class_struct, gpointer cb);

void
gtksharp_cellrenderer_override_get_request_mode (GtkCellRendererClass *class_struct, gpointer cb)
{
	class_struct->get_request_mode = cb;
}

GtkSizeRequestMode gtksharp_cellrenderer_invoke_get_request_mode (GtkCellRendererClass *class_struct, GtkCellRenderer* inst);

GtkSizeRequestMode
gtksharp_cellrenderer_invoke_get_request_mode (GtkCellRendererClass *class_struct, GtkCellRenderer* inst)
{
	if (class_struct->get_request_mode)
		return (* class_struct->get_request_mode) (inst);
	return (GtkSizeRequestMode) 0;
}

void gtksharp_cellrenderer_override_get_preferred_width (GtkCellRendererClass *class_struct, gpointer cb);

void
gtksharp_cellrenderer_override_get_preferred_width (GtkCellRendererClass *class_struct, gpointer cb)
{
	class_struct->get_preferred_width = cb;
}

void gtksharp_cellrenderer_invoke_get_preferred_width (GtkCellRendererClass *class_struct, GtkCellRenderer* inst, GtkWidget* widget, gint* minimum_size, gint* natural_size);

void
gtksharp_cellrenderer_invoke_get_preferred_width (GtkCellRendererClass *class_struct, GtkCellRenderer* inst, GtkWidget* widget, gint* minimum_size, gint* natural_size)
{
	if (class_struct->get_preferred_width)
		(* class_struct->get_preferred_width) (inst, widget, minimum_size, natural_size);
}

void gtksharp_cellrenderer_override_get_preferred_height_for_width (GtkCellRendererClass *class_struct, gpointer cb);

void
gtksharp_cellrenderer_override_get_preferred_height_for_width (GtkCellRendererClass *class_struct, gpointer cb)
{
	class_struct->get_preferred_height_for_width = cb;
}

void gtksharp_cellrenderer_invoke_get_preferred_height_for_width (GtkCellRendererClass *class_struct, GtkCellRenderer* inst, GtkWidget* widget, gint width, gint* minimum_height, gint* natural_height);

void
gtksharp_cellrenderer_invoke_get_preferred_height_for_width (GtkCellRendererClass *class_struct, GtkCellRenderer* inst, GtkWidget* widget, gint width, gint* minimum_height, gint* natural_height)
{
	if (class_struct->get_preferred_height_for_width)
		(* class_struct->get_preferred_height_for_width) (inst, widget, width, minimum_height, natural_height);
}

void gtksharp_cellrenderer_override_get_preferred_height (GtkCellRendererClass *class_struct, gpointer cb);

void
gtksharp_cellrenderer_override_get_preferred_height (GtkCellRendererClass *class_struct, gpointer cb)
{
	class_struct->get_preferred_height = cb;
}

void gtksharp_cellrenderer_invoke_get_preferred_height (GtkCellRendererClass *class_struct, GtkCellRenderer* inst, GtkWidget* widget, gint* minimum_size, gint* natural_size);

void
gtksharp_cellrenderer_invoke_get_preferred_height (GtkCellRendererClass *class_struct, GtkCellRenderer* inst, GtkWidget* widget, gint* minimum_size, gint* natural_size)
{
	if (class_struct->get_preferred_height)
		(* class_struct->get_preferred_height) (inst, widget, minimum_size, natural_size);
}

void gtksharp_cellrenderer_override_get_preferred_width_for_height (GtkCellRendererClass *class_struct, gpointer cb);

void
gtksharp_cellrenderer_override_get_preferred_width_for_height (GtkCellRendererClass *class_struct, gpointer cb)
{
	class_struct->get_preferred_width_for_height = cb;
}

void gtksharp_cellrenderer_invoke_get_preferred_width_for_height (GtkCellRendererClass *class_struct, GtkCellRenderer* inst, GtkWidget* widget, gint height, gint* minimum_width, gint* natural_width);

void
gtksharp_cellrenderer_invoke_get_preferred_width_for_height (GtkCellRendererClass *class_struct, GtkCellRenderer* inst, GtkWidget* widget, gint height, gint* minimum_width, gint* natural_width)
{
	if (class_struct->get_preferred_width_for_height)
		(* class_struct->get_preferred_width_for_height) (inst, widget, height, minimum_width, natural_width);
}

void gtksharp_cellrenderer_override_get_aligned_area (GtkCellRendererClass *class_struct, gpointer cb);

void
gtksharp_cellrenderer_override_get_aligned_area (GtkCellRendererClass *class_struct, gpointer cb)
{
	class_struct->get_aligned_area = cb;
}

void gtksharp_cellrenderer_invoke_get_aligned_area (GtkCellRendererClass *class_struct, GtkCellRenderer* inst, GtkWidget* widget, GtkCellRendererState flags, const GdkRectangle* cell_area, GdkRectangle* aligned_area);

void
gtksharp_cellrenderer_invoke_get_aligned_area (GtkCellRendererClass *class_struct, GtkCellRenderer* inst, GtkWidget* widget, GtkCellRendererState flags, const GdkRectangle* cell_area, GdkRectangle* aligned_area)
{
	if (class_struct->get_aligned_area)
		(* class_struct->get_aligned_area) (inst, widget, flags, cell_area, aligned_area);
}

void gtksharp_cellrenderer_override_render (GtkCellRendererClass *class_struct, gpointer cb);

void
gtksharp_cellrenderer_override_render (GtkCellRendererClass *class_struct, gpointer cb)
{
	class_struct->render = cb;
}

void gtksharp_cellrenderer_invoke_render (GtkCellRendererClass *class_struct, GtkCellRenderer* inst, cairo_t* cr, GtkWidget* widget, const GdkRectangle* background_area, const GdkRectangle* cell_area, GtkCellRendererState flags);

void
gtksharp_cellrenderer_invoke_render (GtkCellRendererClass *class_struct, GtkCellRenderer* inst, cairo_t* cr, GtkWidget* widget, const GdkRectangle* background_area, const GdkRectangle* cell_area, GtkCellRendererState flags)
{
	if (class_struct->render)
		(* class_struct->render) (inst, cr, widget, background_area, cell_area, flags);
}

void gtksharp_cellrenderer_override_activate (GtkCellRendererClass *class_struct, gpointer cb);

void
gtksharp_cellrenderer_override_activate (GtkCellRendererClass *class_struct, gpointer cb)
{
	class_struct->activate = cb;
}

gboolean gtksharp_cellrenderer_invoke_activate (GtkCellRendererClass *class_struct, GtkCellRenderer* inst, GdkEvent* evnt, GtkWidget* widget, const gchar* path, const GdkRectangle* background_area, const GdkRectangle* cell_area, GtkCellRendererState flags);

gboolean
gtksharp_cellrenderer_invoke_activate (GtkCellRendererClass *class_struct, GtkCellRenderer* inst, GdkEvent* evnt, GtkWidget* widget, const gchar* path, const GdkRectangle* background_area, const GdkRectangle* cell_area, GtkCellRendererState flags)
{
	if (class_struct->activate)
		return (* class_struct->activate) (inst, evnt, widget, path, background_area, cell_area, flags);
	return FALSE;
}

void gtksharp_cellrenderer_override_start_editing (GtkCellRendererClass *class_struct, gpointer cb);

void
gtksharp_cellrenderer_override_start_editing (GtkCellRendererClass *class_struct, gpointer cb)
{
	class_struct->start_editing = cb;
}

GtkCellEditable* gtksharp_cellrenderer_invoke_start_editing (GtkCellRendererClass *class_struct, GtkCellRenderer* inst, GdkEvent* evnt, GtkWidget* widget, const gchar* path, const GdkRectangle* background_area, const GdkRectangle* cell_area, GtkCellRendererState flags);

GtkCellEditable*
gtksharp_cellrenderer_invoke_start_editing (GtkCellRendererClass *class_struct, GtkCellRenderer* inst, GdkEvent* evnt, GtkWidget* widget, const gchar* path, const GdkRectangle* background_area, const GdkRectangle* cell_area, GtkCellRendererState flags)
{
	if (class_struct->start_editing)
		return (* class_struct->start_editing) (inst, evnt, widget, path, background_area, cell_area, flags);
	return NULL;
}

void gtksharp_cellrenderer_override_editing_canceled (GtkCellRendererClass *class_struct, gpointer cb);

void
gtksharp_cellrenderer_override_editing_canceled (GtkCellRendererClass *class_struct, gpointer cb)
{
	class_struct->editing_canceled = cb;
}

void gtksharp_cellrenderer_invoke_editing_canceled (GtkCellRendererClass *class_struct, GtkCellRenderer* inst);

void
gtksharp_cellrenderer_invoke_editing_canceled (GtkCellRendererClass *class_struct, GtkCellRenderer* inst)
{
	if (class_struct->editing_canceled)
		(* class_struct->editing_canceled) (inst);
}

void gtksharp_cellrenderer_override_editing_started (GtkCellRendererClass *class_struct, gpointer cb);

void
gtksharp_cellrenderer_override_editing_started (GtkCellRendererClass *class_struct, gpointer cb)
{
	class_struct->editing_started = cb;
}

void gtksharp_cellrenderer_invoke_editing_started (GtkCellRendererClass *class_struct, GtkCellRenderer* inst, GtkCellEditable* editable, const gchar* path);

void
gtksharp_cellrenderer_invoke_editing_started (GtkCellRendererClass *class_struct, GtkCellRenderer* inst, GtkCellEditable* editable, const gchar* path)
{
	if (class_struct->editing_started)
		(* class_struct->editing_started) (inst, editable, path);
}

void gtksharp_container_override_add (GtkContainerClass *class_struct, gpointer cb);

void
gtksharp_container_override_add (GtkContainerClass *class_struct, gpointer cb)
{
	class_struct->add = cb;
}

void gtksharp_container_invoke_add (GtkContainerClass *class_struct, GtkContainer* inst, GtkWidget* widget);

void
gtksharp_container_invoke_add (GtkContainerClass *class_struct, GtkContainer* inst, GtkWidget* widget)
{
	if (class_struct->add)
		(* class_struct->add) (inst, widget);
}

void gtksharp_container_override_remove (GtkContainerClass *class_struct, gpointer cb);

void
gtksharp_container_override_remove (GtkContainerClass *class_struct, gpointer cb)
{
	class_struct->remove = cb;
}

void gtksharp_container_invoke_remove (GtkContainerClass *class_struct, GtkContainer* inst, GtkWidget* widget);

void
gtksharp_container_invoke_remove (GtkContainerClass *class_struct, GtkContainer* inst, GtkWidget* widget)
{
	if (class_struct->remove)
		(* class_struct->remove) (inst, widget);
}

void gtksharp_container_override_check_resize (GtkContainerClass *class_struct, gpointer cb);

void
gtksharp_container_override_check_resize (GtkContainerClass *class_struct, gpointer cb)
{
	class_struct->check_resize = cb;
}

void gtksharp_container_invoke_check_resize (GtkContainerClass *class_struct, GtkContainer* inst);

void
gtksharp_container_invoke_check_resize (GtkContainerClass *class_struct, GtkContainer* inst)
{
	if (class_struct->check_resize)
		(* class_struct->check_resize) (inst);
}

void gtksharp_container_override_set_focus_child (GtkContainerClass *class_struct, gpointer cb);

void
gtksharp_container_override_set_focus_child (GtkContainerClass *class_struct, gpointer cb)
{
	class_struct->set_focus_child = cb;
}

void gtksharp_container_invoke_set_focus_child (GtkContainerClass *class_struct, GtkContainer* inst, GtkWidget* child);

void
gtksharp_container_invoke_set_focus_child (GtkContainerClass *class_struct, GtkContainer* inst, GtkWidget* child)
{
	if (class_struct->set_focus_child)
		(* class_struct->set_focus_child) (inst, child);
}

void gtksharp_container_override_child_type (GtkContainerClass *class_struct, gpointer cb);

void
gtksharp_container_override_child_type (GtkContainerClass *class_struct, gpointer cb)
{
	class_struct->child_type = cb;
}

GType gtksharp_container_invoke_child_type (GtkContainerClass *class_struct, GtkContainer* inst);

GType
gtksharp_container_invoke_child_type (GtkContainerClass *class_struct, GtkContainer* inst)
{
	if (class_struct->child_type)
		return (* class_struct->child_type) (inst);
	return G_TYPE_NONE;
}

void gtksharp_container_override_composite_name (GtkContainerClass *class_struct, gpointer cb);

void
gtksharp_container_override_composite_name (GtkContainerClass *class_struct, gpointer cb)
{
	class_struct->composite_name = cb;
}

gchar* gtksharp_container_invoke_composite_name (GtkContainerClass *class_struct, GtkContainer* inst, GtkWidget* child);

gchar*
gtksharp_container_invoke_composite_name (GtkContainerClass *class_struct, GtkContainer* inst, GtkWidget* child)
{
	if (class_struct->composite_name)
		return (* class_struct->composite_name) (inst, child);
	return NULL;
}

void gtksharp_container_override_set_child_property (GtkContainerClass *class_struct, gpointer cb);

void
gtksharp_container_override_set_child_property (GtkContainerClass *class_struct, gpointer cb)
{
	class_struct->set_child_property = cb;
}

void gtksharp_container_invoke_set_child_property (GtkContainerClass *class_struct, GtkContainer* inst, GtkWidget* child, guint property_id, const GValue* value, GParamSpec* pspec);

void
gtksharp_container_invoke_set_child_property (GtkContainerClass *class_struct, GtkContainer* inst, GtkWidget* child, guint property_id, const GValue* value, GParamSpec* pspec)
{
	if (class_struct->set_child_property)
		(* class_struct->set_child_property) (inst, child, property_id, value, pspec);
}

void gtksharp_container_override_get_child_property (GtkContainerClass *class_struct, gpointer cb);

void
gtksharp_container_override_get_child_property (GtkContainerClass *class_struct, gpointer cb)
{
	class_struct->get_child_property = cb;
}

void gtksharp_container_invoke_get_child_property (GtkContainerClass *class_struct, GtkContainer* inst, GtkWidget* child, guint property_id, GValue* value, GParamSpec* pspec);

void
gtksharp_container_invoke_get_child_property (GtkContainerClass *class_struct, GtkContainer* inst, GtkWidget* child, guint property_id, GValue* value, GParamSpec* pspec)
{
	if (class_struct->get_child_property)
		(* class_struct->get_child_property) (inst, child, property_id, value, pspec);
}

void gtksharp_container_override_get_path_for_child (GtkContainerClass *class_struct, gpointer cb);

void
gtksharp_container_override_get_path_for_child (GtkContainerClass *class_struct, gpointer cb)
{
	class_struct->get_path_for_child = cb;
}

GtkWidgetPath* gtksharp_container_invoke_get_path_for_child (GtkContainerClass *class_struct, GtkContainer* inst, GtkWidget* child);

GtkWidgetPath*
gtksharp_container_invoke_get_path_for_child (GtkContainerClass *class_struct, GtkContainer* inst, GtkWidget* child)
{
	if (class_struct->get_path_for_child)
		return (* class_struct->get_path_for_child) (inst, child);
	return NULL;
}

void gtksharp_menuitem_override_activate (GtkMenuItemClass *class_struct, gpointer cb);

void
gtksharp_menuitem_override_activate (GtkMenuItemClass *class_struct, gpointer cb)
{
	class_struct->activate = cb;
}

void gtksharp_menuitem_invoke_activate (GtkMenuItemClass *class_struct, GtkMenuItem* inst);

void
gtksharp_menuitem_invoke_activate (GtkMenuItemClass *class_struct, GtkMenuItem* inst)
{
	if (class_struct->activate)
		(* class_struct->activate) (inst);
}

void gtksharp_menuitem_override_activate_item (GtkMenuItemClass *class_struct, gpointer cb);

void
gtksharp_menuitem_override_activate_item (GtkMenuItemClass *class_struct, gpointer cb)
{
	class_struct->activate_item = cb;
}

void gtksharp_menuitem_invoke_activate_item (GtkMenuItemClass *class_struct, GtkMenuItem* inst);

void
gtksharp_menuitem_invoke_activate_item (GtkMenuItemClass *class_struct, GtkMenuItem* inst)
{
	if (class_struct->activate_item)
		(* class_struct->activate_item) (inst);
}

void gtksharp_menuitem_override_toggle_size_request (GtkMenuItemClass *class_struct, gpointer cb);

void
gtksharp_menuitem_override_toggle_size_request (GtkMenuItemClass *class_struct, gpointer cb)
{
	class_struct->toggle_size_request = cb;
}

void gtksharp_menuitem_invoke_toggle_size_request (GtkMenuItemClass *class_struct, GtkMenuItem* inst, gint* requisition);

void
gtksharp_menuitem_invoke_toggle_size_request (GtkMenuItemClass *class_struct, GtkMenuItem* inst, gint* requisition)
{
	if (class_struct->toggle_size_request)
		(* class_struct->toggle_size_request) (inst, requisition);
}

void gtksharp_menuitem_override_toggle_size_allocate (GtkMenuItemClass *class_struct, gpointer cb);

void
gtksharp_menuitem_override_toggle_size_allocate (GtkMenuItemClass *class_struct, gpointer cb)
{
	class_struct->toggle_size_allocate = cb;
}

void gtksharp_menuitem_invoke_toggle_size_allocate (GtkMenuItemClass *class_struct, GtkMenuItem* inst, gint allocation);

void
gtksharp_menuitem_invoke_toggle_size_allocate (GtkMenuItemClass *class_struct, GtkMenuItem* inst, gint allocation)
{
	if (class_struct->toggle_size_allocate)
		(* class_struct->toggle_size_allocate) (inst, allocation);
}

void gtksharp_menuitem_override_set_label (GtkMenuItemClass *class_struct, gpointer cb);

void
gtksharp_menuitem_override_set_label (GtkMenuItemClass *class_struct, gpointer cb)
{
	class_struct->set_label = cb;
}

void gtksharp_menuitem_invoke_set_label (GtkMenuItemClass *class_struct, GtkMenuItem* inst, const gchar* label);

void
gtksharp_menuitem_invoke_set_label (GtkMenuItemClass *class_struct, GtkMenuItem* inst, const gchar* label)
{
	if (class_struct->set_label)
		(* class_struct->set_label) (inst, label);
}

void gtksharp_menuitem_override_get_label (GtkMenuItemClass *class_struct, gpointer cb);

void
gtksharp_menuitem_override_get_label (GtkMenuItemClass *class_struct, gpointer cb)
{
	class_struct->get_label = cb;
}

gchar* gtksharp_menuitem_invoke_get_label (GtkMenuItemClass *class_struct, GtkMenuItem* inst);

gchar*
gtksharp_menuitem_invoke_get_label (GtkMenuItemClass *class_struct, GtkMenuItem* inst)
{
	if (class_struct->get_label)
		return (* class_struct->get_label) (inst);
	return NULL;
}

void gtksharp_menuitem_override_select (GtkMenuItemClass *class_struct, gpointer cb);

void
gtksharp_menuitem_override_select (GtkMenuItemClass *class_struct, gpointer cb)
{
	class_struct->select = cb;
}

void gtksharp_menuitem_invoke_select (GtkMenuItemClass *class_struct, GtkMenuItem* inst);

void
gtksharp_menuitem_invoke_select (GtkMenuItemClass *class_struct, GtkMenuItem* inst)
{
	if (class_struct->select)
		(* class_struct->select) (inst);
}

void gtksharp_menuitem_override_deselect (GtkMenuItemClass *class_struct, gpointer cb);

void
gtksharp_menuitem_override_deselect (GtkMenuItemClass *class_struct, gpointer cb)
{
	class_struct->deselect = cb;
}

void gtksharp_menuitem_invoke_deselect (GtkMenuItemClass *class_struct, GtkMenuItem* inst);

void
gtksharp_menuitem_invoke_deselect (GtkMenuItemClass *class_struct, GtkMenuItem* inst)
{
	if (class_struct->deselect)
		(* class_struct->deselect) (inst);
}

void gtksharp_menushell_override_deactivate (GtkMenuShellClass *class_struct, gpointer cb);

void
gtksharp_menushell_override_deactivate (GtkMenuShellClass *class_struct, gpointer cb)
{
	class_struct->deactivate = cb;
}

void gtksharp_menushell_invoke_deactivate (GtkMenuShellClass *class_struct, GtkMenuShell* inst);

void
gtksharp_menushell_invoke_deactivate (GtkMenuShellClass *class_struct, GtkMenuShell* inst)
{
	if (class_struct->deactivate)
		(* class_struct->deactivate) (inst);
}

void gtksharp_menushell_override_selection_done (GtkMenuShellClass *class_struct, gpointer cb);

void
gtksharp_menushell_override_selection_done (GtkMenuShellClass *class_struct, gpointer cb)
{
	class_struct->selection_done = cb;
}

void gtksharp_menushell_invoke_selection_done (GtkMenuShellClass *class_struct, GtkMenuShell* inst);

void
gtksharp_menushell_invoke_selection_done (GtkMenuShellClass *class_struct, GtkMenuShell* inst)
{
	if (class_struct->selection_done)
		(* class_struct->selection_done) (inst);
}

void gtksharp_menushell_override_move_current (GtkMenuShellClass *class_struct, gpointer cb);

void
gtksharp_menushell_override_move_current (GtkMenuShellClass *class_struct, gpointer cb)
{
	class_struct->move_current = cb;
}

void gtksharp_menushell_invoke_move_current (GtkMenuShellClass *class_struct, GtkMenuShell* inst, GtkMenuDirectionType direction);

void
gtksharp_menushell_invoke_move_current (GtkMenuShellClass *class_struct, GtkMenuShell* inst, GtkMenuDirectionType direction)
{
	if (class_struct->move_current)
		(* class_struct->move_current) (inst, direction);
}

void gtksharp_menushell_override_activate_current (GtkMenuShellClass *class_struct, gpointer cb);

void
gtksharp_menushell_override_activate_current (GtkMenuShellClass *class_struct, gpointer cb)
{
	class_struct->activate_current = cb;
}

void gtksharp_menushell_invoke_activate_current (GtkMenuShellClass *class_struct, GtkMenuShell* inst, gboolean force_hide);

void
gtksharp_menushell_invoke_activate_current (GtkMenuShellClass *class_struct, GtkMenuShell* inst, gboolean force_hide)
{
	if (class_struct->activate_current)
		(* class_struct->activate_current) (inst, force_hide);
}

void gtksharp_menushell_override_cancel (GtkMenuShellClass *class_struct, gpointer cb);

void
gtksharp_menushell_override_cancel (GtkMenuShellClass *class_struct, gpointer cb)
{
	class_struct->cancel = cb;
}

void gtksharp_menushell_invoke_cancel (GtkMenuShellClass *class_struct, GtkMenuShell* inst);

void
gtksharp_menushell_invoke_cancel (GtkMenuShellClass *class_struct, GtkMenuShell* inst)
{
	if (class_struct->cancel)
		(* class_struct->cancel) (inst);
}

void gtksharp_menushell_override_select_item (GtkMenuShellClass *class_struct, gpointer cb);

void
gtksharp_menushell_override_select_item (GtkMenuShellClass *class_struct, gpointer cb)
{
	class_struct->select_item = cb;
}

void gtksharp_menushell_invoke_select_item (GtkMenuShellClass *class_struct, GtkMenuShell* inst, GtkWidget* menu_item);

void
gtksharp_menushell_invoke_select_item (GtkMenuShellClass *class_struct, GtkMenuShell* inst, GtkWidget* menu_item)
{
	if (class_struct->select_item)
		(* class_struct->select_item) (inst, menu_item);
}

void gtksharp_menushell_override_insert (GtkMenuShellClass *class_struct, gpointer cb);

void
gtksharp_menushell_override_insert (GtkMenuShellClass *class_struct, gpointer cb)
{
	class_struct->insert = cb;
}

void gtksharp_menushell_invoke_insert (GtkMenuShellClass *class_struct, GtkMenuShell* inst, GtkWidget* child, gint position);

void
gtksharp_menushell_invoke_insert (GtkMenuShellClass *class_struct, GtkMenuShell* inst, GtkWidget* child, gint position)
{
	if (class_struct->insert)
		(* class_struct->insert) (inst, child, position);
}

void gtksharp_menushell_override_get_popup_delay (GtkMenuShellClass *class_struct, gpointer cb);

void
gtksharp_menushell_override_get_popup_delay (GtkMenuShellClass *class_struct, gpointer cb)
{
	class_struct->get_popup_delay = cb;
}

gint gtksharp_menushell_invoke_get_popup_delay (GtkMenuShellClass *class_struct, GtkMenuShell* inst);

gint
gtksharp_menushell_invoke_get_popup_delay (GtkMenuShellClass *class_struct, GtkMenuShell* inst)
{
	if (class_struct->get_popup_delay)
		return (* class_struct->get_popup_delay) (inst);
	return 0;
}

void gtksharp_menushell_override_move_selected (GtkMenuShellClass *class_struct, gpointer cb);

void
gtksharp_menushell_override_move_selected (GtkMenuShellClass *class_struct, gpointer cb)
{
	class_struct->move_selected = cb;
}

gboolean gtksharp_menushell_invoke_move_selected (GtkMenuShellClass *class_struct, GtkMenuShell* inst, gint distance);

gboolean
gtksharp_menushell_invoke_move_selected (GtkMenuShellClass *class_struct, GtkMenuShell* inst, gint distance)
{
	if (class_struct->move_selected)
		return (* class_struct->move_selected) (inst, distance);
	return FALSE;
}

void gtksharp_range_override_value_changed (GtkRangeClass *class_struct, gpointer cb);

void
gtksharp_range_override_value_changed (GtkRangeClass *class_struct, gpointer cb)
{
	class_struct->value_changed = cb;
}

void gtksharp_range_invoke_value_changed (GtkRangeClass *class_struct, GtkRange* inst);

void
gtksharp_range_invoke_value_changed (GtkRangeClass *class_struct, GtkRange* inst)
{
	if (class_struct->value_changed)
		(* class_struct->value_changed) (inst);
}

void gtksharp_range_override_adjust_bounds (GtkRangeClass *class_struct, gpointer cb);

void
gtksharp_range_override_adjust_bounds (GtkRangeClass *class_struct, gpointer cb)
{
	class_struct->adjust_bounds = cb;
}

void gtksharp_range_invoke_adjust_bounds (GtkRangeClass *class_struct, GtkRange* inst, gdouble new_value);

void
gtksharp_range_invoke_adjust_bounds (GtkRangeClass *class_struct, GtkRange* inst, gdouble new_value)
{
	if (class_struct->adjust_bounds)
		(* class_struct->adjust_bounds) (inst, new_value);
}

void gtksharp_range_override_move_slider (GtkRangeClass *class_struct, gpointer cb);

void
gtksharp_range_override_move_slider (GtkRangeClass *class_struct, gpointer cb)
{
	class_struct->move_slider = cb;
}

void gtksharp_range_invoke_move_slider (GtkRangeClass *class_struct, GtkRange* inst, GtkScrollType scroll);

void
gtksharp_range_invoke_move_slider (GtkRangeClass *class_struct, GtkRange* inst, GtkScrollType scroll)
{
	if (class_struct->move_slider)
		(* class_struct->move_slider) (inst, scroll);
}

void gtksharp_range_override_get_range_border (GtkRangeClass *class_struct, gpointer cb);

void
gtksharp_range_override_get_range_border (GtkRangeClass *class_struct, gpointer cb)
{
	class_struct->get_range_border = cb;
}

void gtksharp_range_invoke_get_range_border (GtkRangeClass *class_struct, GtkRange* inst, GtkBorder* border_);

void
gtksharp_range_invoke_get_range_border (GtkRangeClass *class_struct, GtkRange* inst, GtkBorder* border_)
{
	if (class_struct->get_range_border)
		(* class_struct->get_range_border) (inst, border_);
}

void gtksharp_range_override_change_value (GtkRangeClass *class_struct, gpointer cb);

void
gtksharp_range_override_change_value (GtkRangeClass *class_struct, gpointer cb)
{
	class_struct->change_value = cb;
}

gboolean gtksharp_range_invoke_change_value (GtkRangeClass *class_struct, GtkRange* inst, GtkScrollType scroll, gdouble new_value);

gboolean
gtksharp_range_invoke_change_value (GtkRangeClass *class_struct, GtkRange* inst, GtkScrollType scroll, gdouble new_value)
{
	if (class_struct->change_value)
		return (* class_struct->change_value) (inst, scroll, new_value);
	return FALSE;
}

void gtksharp_range_override_get_range_size_request (GtkRangeClass *class_struct, gpointer cb);

void
gtksharp_range_override_get_range_size_request (GtkRangeClass *class_struct, gpointer cb)
{
	class_struct->get_range_size_request = cb;
}

void gtksharp_range_invoke_get_range_size_request (GtkRangeClass *class_struct, GtkRange* inst, GtkOrientation orientation, gint* minimum, gint* natural);

void
gtksharp_range_invoke_get_range_size_request (GtkRangeClass *class_struct, GtkRange* inst, GtkOrientation orientation, gint* minimum, gint* natural)
{
	if (class_struct->get_range_size_request)
		(* class_struct->get_range_size_request) (inst, orientation, minimum, natural);
}

guint gtksharp_gtk_rcstyle_get_name_offset (void);

guint
gtksharp_gtk_rcstyle_get_name_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GtkRcStyle, name);
}

guint gtksharp_gtk_rcstyle_get_font_desc_offset (void);

guint
gtksharp_gtk_rcstyle_get_font_desc_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GtkRcStyle, font_desc);
}

guint gtksharp_gtk_rcstyle_get_xthickness_offset (void);

guint
gtksharp_gtk_rcstyle_get_xthickness_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GtkRcStyle, xthickness);
}

guint gtksharp_gtk_rcstyle_get_ythickness_offset (void);

guint
gtksharp_gtk_rcstyle_get_ythickness_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GtkRcStyle, ythickness);
}

guint gtksharp_gtk_style_get_black_offset (void);

guint
gtksharp_gtk_style_get_black_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GtkStyle, black);
}

guint gtksharp_gtk_style_get_white_offset (void);

guint
gtksharp_gtk_style_get_white_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GtkStyle, white);
}

guint gtksharp_gtk_style_get_font_desc_offset (void);

guint
gtksharp_gtk_style_get_font_desc_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GtkStyle, font_desc);
}

guint gtksharp_gtk_style_get_xthickness_offset (void);

guint
gtksharp_gtk_style_get_xthickness_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GtkStyle, xthickness);
}

guint gtksharp_gtk_style_get_ythickness_offset (void);

guint
gtksharp_gtk_style_get_ythickness_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GtkStyle, ythickness);
}

GtkAccelFlags gtksharp_gtk_accelkey_get_accel_flags (GtkAccelKey *accelkey);
void gtksharp_gtk_accelkey_set_accel_flags (GtkAccelKey *accelkey, GtkAccelFlags value);

GtkAccelFlags
gtksharp_gtk_accelkey_get_accel_flags (GtkAccelKey *accelkey)
{
	return (GtkAccelFlags)accelkey->accel_flags;
}

void
gtksharp_gtk_accelkey_set_accel_flags (GtkAccelKey *accelkey, GtkAccelFlags value)
{
	accelkey->accel_flags = (GtkAccelFlags)value;
}

PangoUnderline gtksharp_gtk_textappearance_get_underline (GtkTextAppearance *textappearance);
void gtksharp_gtk_textappearance_set_underline (GtkTextAppearance *textappearance, PangoUnderline value);

PangoUnderline
gtksharp_gtk_textappearance_get_underline (GtkTextAppearance *textappearance)
{
	return (PangoUnderline)textappearance->underline;
}

void
gtksharp_gtk_textappearance_set_underline (GtkTextAppearance *textappearance, PangoUnderline value)
{
	textappearance->underline = (PangoUnderline)value;
}

gboolean gtksharp_gtk_textappearance_get_strikethrough (GtkTextAppearance *textappearance);
void gtksharp_gtk_textappearance_set_strikethrough (GtkTextAppearance *textappearance, gboolean value);

gboolean
gtksharp_gtk_textappearance_get_strikethrough (GtkTextAppearance *textappearance)
{
	return (gboolean)textappearance->strikethrough;
}

void
gtksharp_gtk_textappearance_set_strikethrough (GtkTextAppearance *textappearance, gboolean value)
{
	textappearance->strikethrough = (gboolean)value;
}

guint gtksharp_gtk_textattributes_get_justification_offset (void);

guint
gtksharp_gtk_textattributes_get_justification_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GtkTextAttributes, justification);
}

guint gtksharp_gtk_textattributes_get_direction_offset (void);

guint
gtksharp_gtk_textattributes_get_direction_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GtkTextAttributes, direction);
}

guint gtksharp_gtk_textattributes_get_font_offset (void);

guint
gtksharp_gtk_textattributes_get_font_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GtkTextAttributes, font);
}

guint gtksharp_gtk_textattributes_get_font_scale_offset (void);

guint
gtksharp_gtk_textattributes_get_font_scale_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GtkTextAttributes, font_scale);
}

guint gtksharp_gtk_textattributes_get_left_margin_offset (void);

guint
gtksharp_gtk_textattributes_get_left_margin_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GtkTextAttributes, left_margin);
}

guint gtksharp_gtk_textattributes_get_right_margin_offset (void);

guint
gtksharp_gtk_textattributes_get_right_margin_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GtkTextAttributes, right_margin);
}

guint gtksharp_gtk_textattributes_get_indent_offset (void);

guint
gtksharp_gtk_textattributes_get_indent_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GtkTextAttributes, indent);
}

guint gtksharp_gtk_textattributes_get_pixels_above_lines_offset (void);

guint
gtksharp_gtk_textattributes_get_pixels_above_lines_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GtkTextAttributes, pixels_above_lines);
}

guint gtksharp_gtk_textattributes_get_pixels_below_lines_offset (void);

guint
gtksharp_gtk_textattributes_get_pixels_below_lines_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GtkTextAttributes, pixels_below_lines);
}

guint gtksharp_gtk_textattributes_get_pixels_inside_wrap_offset (void);

guint
gtksharp_gtk_textattributes_get_pixels_inside_wrap_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GtkTextAttributes, pixels_inside_wrap);
}

guint gtksharp_gtk_textattributes_get_tabs_offset (void);

guint
gtksharp_gtk_textattributes_get_tabs_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GtkTextAttributes, tabs);
}

guint gtksharp_gtk_textattributes_get_wrap_mode_offset (void);

guint
gtksharp_gtk_textattributes_get_wrap_mode_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GtkTextAttributes, wrap_mode);
}

guint gtksharp_gtk_textattributes_get_language_offset (void);

guint
gtksharp_gtk_textattributes_get_language_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GtkTextAttributes, language);
}

gboolean gtksharp_gtk_textattributes_get_invisible (GtkTextAttributes *textattributes);
void gtksharp_gtk_textattributes_set_invisible (GtkTextAttributes *textattributes, gboolean value);

gboolean
gtksharp_gtk_textattributes_get_invisible (GtkTextAttributes *textattributes)
{
	return (gboolean)textattributes->invisible;
}

void
gtksharp_gtk_textattributes_set_invisible (GtkTextAttributes *textattributes, gboolean value)
{
	textattributes->invisible = (gboolean)value;
}

gboolean gtksharp_gtk_textattributes_get_bg_full_height (GtkTextAttributes *textattributes);
void gtksharp_gtk_textattributes_set_bg_full_height (GtkTextAttributes *textattributes, gboolean value);

gboolean
gtksharp_gtk_textattributes_get_bg_full_height (GtkTextAttributes *textattributes)
{
	return (gboolean)textattributes->bg_full_height;
}

void
gtksharp_gtk_textattributes_set_bg_full_height (GtkTextAttributes *textattributes, gboolean value)
{
	textattributes->bg_full_height = (gboolean)value;
}

gboolean gtksharp_gtk_textattributes_get_editable (GtkTextAttributes *textattributes);
void gtksharp_gtk_textattributes_set_editable (GtkTextAttributes *textattributes, gboolean value);

gboolean
gtksharp_gtk_textattributes_get_editable (GtkTextAttributes *textattributes)
{
	return (gboolean)textattributes->editable;
}

void
gtksharp_gtk_textattributes_set_editable (GtkTextAttributes *textattributes, gboolean value)
{
	textattributes->editable = (gboolean)value;
}

gboolean gtksharp_gtk_textattributes_get_no_fallback (GtkTextAttributes *textattributes);
void gtksharp_gtk_textattributes_set_no_fallback (GtkTextAttributes *textattributes, gboolean value);

gboolean
gtksharp_gtk_textattributes_get_no_fallback (GtkTextAttributes *textattributes)
{
	return (gboolean)textattributes->no_fallback;
}

void
gtksharp_gtk_textattributes_set_no_fallback (GtkTextAttributes *textattributes, gboolean value)
{
	textattributes->no_fallback = (gboolean)value;
}

guint gtksharp_gtk_textattributes_get_letter_spacing_offset (void);

guint
gtksharp_gtk_textattributes_get_letter_spacing_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GtkTextAttributes, letter_spacing);
}

guint gtksharp_gtk_textattributes_get_font_features_offset (void);

guint
gtksharp_gtk_textattributes_get_font_features_offset (void)
{
	return (guint)G_STRUCT_OFFSET (GtkTextAttributes, font_features);
}

